# Generated by Django 6.0.4 on 2026-05-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/'),
        ),
    ]
